---
title: "P8108 Survival Analysis Heart Failure"
author: "Yi Huang"
date: "2023-11-10"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE)
```

## Preparation
install and read packages, read functions
```{r set up}
#----------------------------------------------------------------
# CLEAR ENVIRONMENT
#----------------------------------------------------------------
rm(list = ls())

#----------------------------------------------------------------
# INSTALL PACKAGES
#----------------------------------------------------------------
packages <- c("dplyr", "tidyverse", "readxl", 
              "survival", "KMsurv", 
              # ggsurvplot()
              "survminer",
              # stepwiseCox()
              "StepReg")


# Install missing packages
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], dependencies = TRUE)
}

# Load packages invisibly
invisible(lapply(packages, library, character.only = TRUE))

# Remove variables associated with package installation
rm(packages, installed_packages)

# Read function
source("shared_code/stepwiseCox.R", local = TRUE)
# source("shared_code/stepwiseCox.R", local = TRUE)$value
```


## Load data

```{r}
# read data
data <- read_csv("data/heart_failure.csv")

# # data cleaning
data <- data |>
  arrange(TIME) |>
  janitor::clean_names() |>
  mutate(gender = factor(gender),
         smoking = factor(smoking),
         diabetes = factor(diabetes),
         bp = factor(bp),
         # event = factor(event),
         anaemia = factor(anaemia)) |>
  rename(pletelets = pletelets)
```

## Cox model

**Full model**
```{r}
# use survival to fit a cox model
cox_model <- coxph(Surv(time, event) ~ gender + smoking + diabetes + bp + anaemia + age + ejection_fraction + sodium + creatinine + pletelets + cpk, data = data)
summary(cox_model)
```


```{r example}
# # stepwiseCox example
# lung <- survival::lung
# 
# my.data <- na.omit(lung)
# my.data$status
# 
# my.data$status1 <- ifelse(my.data$status==2,1,0)
# 
# data <- my.data
# 
# formula = Surv(time, status1) ~ . - status 
# 
# stepwiseCox(formula=formula,
#             data=my.data,
#             selection="bidirection",
#             select="HQ",
#             method="efron")
```

## Variable Selection

```{r}
stepwise_data <- read_csv("data/heart_failure.csv")
## data cleaning for stepwiseCox, variables need to be all numeric
stepwise_data <- stepwise_data |>
  arrange(TIME) |>
  janitor::clean_names()

# Variable selection using stepwise Cox model
stepwise_model <- stepwiseCox(Surv(time, event) ~ gender + smoking + diabetes + bp + anaemia + age + ejection_fraction + sodium + creatinine + pletelets + cpk, data = stepwise_data)

stepwise_model
```

**consider transformation on left-skewed predictors**

```{r}
stepwise_data <- stepwise_data %>%
  mutate(logcpk = log(cpk+1),
         logcre=log(creatinine+1))

# Variable selection using stepwise Cox model
stepwise_model <- stepwiseCox(Surv(time, event) ~ gender + smoking + diabetes + bp + 
                                anaemia + age + ejection_fraction + sodium + logcre + 
                                pletelets + logcpk, data = stepwise_data)
stepwise_model
```


## Check assumptions for Cox model

```{r}
# Check assumptions with cox.zph
# full model
cox_zph <- cox.zph(cox_model)
plot(cox_zph) # Residual plots

# Plot survival curves
ggsurvplot(survfit(cox_model), data = data, conf.int = TRUE)
```

```{r}
# refit a model with 7 selected variables 
# bp, anaemia, age, ejection_fraction, sodium, creatinine, cpk
step_model <- coxph(Surv(time, event) ~ bp + anaemia + age + ejection_fraction + sodium + 
                      creatinine + cpk, data = stepwise_data)
summary(step_model)

# Check assumptions with model obtained from stepwiseCox
cox_step <- cox.zph(step_model)
plot(cox_step) # Residual plots

# Plot survival curves
ggsurvplot(survfit(step_model), data = data, conf.int = TRUE)
```

