---
title: "EDA"
author: "Runze Cui"
date: "2023-11-10"
output: pdf_document
header-includes:
- \usepackage{booktabs}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(survival)
library(writexl)
library(readxl)
library(table1)
```

## Read File

```{r echo=T}
dat <- read_csv("./data/heart_failure.csv") %>% 
  arrange(TIME) %>% janitor::clean_names() %>% 
  mutate(gender = factor(gender), 
         smoking = factor(smoking),
         diabetes = factor(diabetes),
         bp = factor(bp),
         event = factor(event),
         anaemia = factor(anaemia)) %>% 
  rename(platelets = pletelets)
# write_xlsx(dat, "./data/dat.xlsx")
# read_excel("./data/dat.xlsx")
dat_overview = head(dat)
```

## EDA:

- 299 patients of heart failure comprising of 105 women and 194 men.
- All the patients were more than 40 years old.

**Discrete Variable:** event (indicator), gender, smoking, diabetes, bp and anaemia.

**Continuous Variable:** time, age, ejection_fraction (EF), sodium, creatinine, pletelets and cpk.


```{r results='asis'}
label(dat$time) = "Survival time (days)"
label(dat$event) = "Event indicator (censored = 0, event = 1)"
label(dat$gender) = "Gender (female = 0, male = 1)"
label(dat$smoking) = "Smoking status (non-smoker = 0, smoker = 1)"
label(dat$diabetes) = "Diabetes (no diabetes = 0, diabetes = 1)"
label(dat$bp) = "Blood Pressure (normal = 0, hypertension = 1)"
label(dat$anaemia) = "Anaemia (no anaemia = 0, anaemia = 1)"
label(dat$age) = "Age"
label(dat$ejection_fraction) = "Ejection Fraction (EF)"
label(dat$sodium) = "Serum Sodium"
label(dat$creatinine) = "Serum creatinine"
label(dat$platelets) = "Plateletes"
label(dat$cpk) = "CPK"

t1 = table1(~ event + gender + smoking + diabetes + bp + anaemia, 
                  data = dat, topclass = "Rtable1-zebra")
t2 = table1(~ time + age + ejection_fraction + sodium + creatinine + platelets + cpk, 
                   data = dat, topclass = "Rtable1-zebra")
t1
t2
```

