---
title: "Paramatric Model"
author: "Yi Huang"
date: "2023-12-08"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE)

#----------------------------------------------------------------
# CLEAR ENVIRONMENT
#----------------------------------------------------------------
rm(list = ls())

#----------------------------------------------------------------
# INSTALL PACKAGES
#----------------------------------------------------------------
packages <- c("dplyr", "tidyverse", "readxl", 
              "survival", "KMsurv", 
              "survminer","flexsurv",
              "eha",
              "knitr",
              "kableExtra")


# Install missing packages
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], dependencies = TRUE)
}

# Load packages invisibly
invisible(lapply(packages, library, character.only = TRUE))

# Remove variables associated with package installation
rm(packages, installed_packages)

# Theme set
theme_set(theme_minimal())
```


```{r, include=FALSE}
# read data
raw_data <- read_csv("data/heart_failure.csv")

# clean variable names
raw_data <- raw_data |>
  arrange(TIME) |>
  janitor::clean_names()

## data cleaning, create data frame for model
model_data <- raw_data |>
  mutate(gender = factor(gender),
         smoking = factor(smoking),
         diabetes = factor(diabetes),
         bp = factor(bp),
         # event = factor(event),
         anaemia = factor(anaemia),
         logcre=log(creatinine+1),
         logcpk = log(cpk+1)) |>
  rename(pletelets = pletelets)|>
  mutate(ef_cat = factor(case_when(
    ejection_fraction <= 30 ~ "Low",
    ejection_fraction > 30 & ejection_fraction < 45 ~ "Medium",
    ejection_fraction >= 45 ~ "High"),
    levels = c("Low", "Medium", "High")))

## create dummy variable for categorical variable
heart_data <- model.matrix(ejection_fraction~ef_cat, data = model_data)[,-1] |>
  as.data.frame()

## create data frame for stepwiseCox
heart_data <- cbind(raw_data, heart_data) 
stepwise_data <- heart_data |>
  mutate(logcre=log(creatinine+1),
         logcpk = log(cpk+1)) |>
  dplyr::select(-creatinine, -cpk, -ejection_fraction)
```

## Parametric models

Weibull model selection:\
         Df    AIC\
- \<none>\    1273.2\
- sodium  1 1273.5\
- bp      1 1277.8\
- logcre  1 1282.9\
- ef_cat  2 1294.7\
- age     1 1298.1\
\
\
Gompertz model selection: \
DF AIC\
- \<none>\   1273.6\
- anaemia  1 1273.6\
- sodium   1 1274.5\
- bp       1 1278.2\
- logcre   1 1283.6\
- ef_cat   2 1294.8\
- age      1 1298.9\

## Weibull

```{r}
fit_weibull = phreg(Surv(time, event) ~ gender + smoking + diabetes + bp + anaemia + 
                  age + ef_cat+ sodium + pletelets + logcre + logcpk, 
                data = model_data, dist = "weibull")
summary(fit_weibull)

# AIC Both direction
library(MASS)
stepAIC(fit_weibull)

final_weibull <- phreg(formula = Surv(time, event) ~ bp + age + ef_catMedium + 
                          ef_catHigh + sodium + logcre, data = stepwise_data, dist = "weibull")

final_weibull
```

```{r}
1 - pchisq((0.477/0.212876134)^2, df = 1)

# Extract relevant information
weibull_summary <- data.frame(
  Variable= c(names(final_weibull$coefficients)),
  Coef = round(as.vector(final_weibull$coefficients),4),
  `Exp(Coef)` = round(exp(as.vector(final_weibull$coefficients)),4),
  `se(Coef)` = round(sqrt(as.vector(diag(final_weibull[["var"]]))),4),
  `Wald p` = round(1-pchisq((as.vector(final_weibull$coefficients)/sqrt(as.vector(diag(final_weibull[["var"]]))))^2,1),4))

# Create table using kable
kable(weibull_summary, caption = "Summary of Gompertz PH Model Fitting", digits = 4) 
# |> kable_styling(latex_options = c("striped", "hold_position"))
```

## Gompertz

```{r}
fit_gompertz = phreg(Surv(time, event) ~ gender + smoking + diabetes + bp + anaemia + 
                  age + ef_cat+ sodium + pletelets + logcre + logcpk, 
                data = model_data, dist = "gompertz")
fit_gompertz

# AIC Both direction
stepAIC(fit_gompertz, direction = "backward")

final_gompertz <- phreg(formula = Surv(time, event) ~ bp + anaemia + age + ef_catMedium + 
                          ef_catHigh + sodium + logcre, data = stepwise_data, dist = "gompertz")

final_gompertz
```

```{r}
# Extract relevant information
gompertz_summary <- data.frame(
  Variable= c(names(final_gompertz$coefficients)),
  Coef = round(as.vector(final_gompertz$coefficients),4),
  `Exp(Coef)` = round(exp(as.vector(final_gompertz$coefficients)),4),
  `se(Coef)` = round(sqrt(as.vector(diag(final_gompertz[["var"]]))),4),
  `Wald p` = round(1-pchisq((as.vector(final_gompertz$coefficients)/sqrt(as.vector(diag(final_gompertz[["var"]]))))^2,1),4))

# Create table using kable
kable(gompertz_summary, caption = "Summary of Weibul PH Model Fitting", digits = 4) 
# |> kable_styling(latex_options = c("striped", "hold_position"))
```

